# Site settings
title: "Monte Production"
email: montepro@inbox.ru
description: "Организация мероприятий, видеопродакшн, постпродакшн"
baseurl: ""
url: "http://monteproduction.ru/"
title_description: "Организация мероприятий, видеопродакшн, постпродакшн"
title_image: 
google_analytics: 
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: KlimovRV
github_username:  Klimov-RV
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://t.me/klimovrv\">@klimovrv</a>"
footer_right: "&lt;/&gt; <a href=\"https://github.com/monteproduction/monteproduction.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: none
exclude: [vendor]
